export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const SAVE_USER_SHIPPING_ADDRESS = "SAVE_USER_SHIPPING_ADDRESS";
export const SAVE_USER_PAYMENT_METHOD = "SAVE_USER_PAYMENT_METHOD";
