export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL";
export const PAY_ORDER_RESET = "PAY_ORDER_RESET";

export const LIST_USER_REQUEST_ORDER = "LIST_USER_REQUEST_ORDER";
export const LIST_USER_SUCCESS_ORDER = "LIST_USER_SUCCESS_ORDER";
export const LIST_USER_FAIL_ORDER = "LIST_USER_FAIL_ORDER";
export const LIST_USER_RESET_ORDER = "LIST_USER_RESET_ORDER";

export const DETAILS_ORDER_REQUEST = "DETAILS_ORDER_REQUEST";
export const DETAILS_ORDER_SUCCESS = "DETAILS_ORDER_SUCCESS";
export const DETAILS_ORDER_FAIL = "DETAILS_ORDER_FAIL";

export const DELIVER_ORDER_REQUEST = "DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAIL = "DELIVER_ORDER_FAIL";
export const DELIVER_ORDER_RESET = "DELIVER_ORDER_RESET";

export const LIST_ORDER_REQUEST = "LIST_ORDER_REQUEST";
export const LIST_ORDER_SUCCESS = "LIST_ORDER_SUCCESS";
export const LIST_ORDER_FAIL = "LIST_ORDER_FAIL";
